Feature/#90 add different colors of usernames
SkillChat/SkillChat pull request #108
Opened 2021-09-29 11:58 UTC by UnluckyD

2021-09-29 18:07 UTC, EgorTrubnikov approved these changes

2021-09-30 09:21 UTC, KlinskiyDD reviewed
Все класно работает. Есть пару замечаний в коде. Я думаю, что Паша сможет более точно внести правки.

Правильно ли я понял, что цвета у пользователей должны быть разными при каждом новом запуске? Если да, то этот эффект не достигнут.

2021-09-30 09:21 UTC, KlinskiyDD commented on SkillChat.Client/Program.cs
> +        }
Мне кажется, что здесь этому не место. Я думаю, что нужно вынести в отдельный класс.

2021-09-30 09:21 UTC, KlinskiyDD commented on SkillChat.Client.ViewModel/ColorGetter.cs
> +        };
Возможно стоило реализовать через enum.
По аналогии с тем, как реализованы цвета в консоли

2021-09-30 11:41 UTC, UnluckyD commented on SkillChat.Client/Program.cs
> +        }
Исправил

2021-10-01 18:36 UTC, EgorTrubnikov commented on SkillChat.Client.ViewModel/ColorGeneratorClass.cs
> +}
Миша, вот этот класс не должен находиться в SkillChat.Client.ViewModel, т.к. использует Авалонию. 
Это мне Паша обьяснял примерно на таком же кейсе. Ты интерфейс IColorGenerator написал в SkillChat.Client.ViewModel, а этот класс должен быть в SkillChat.Client, ты в SkillChat.Client.Programm.cs 
регистрируешь его: Locator.CurrentMutable.Register<IColorGenerator>(() => new ColorGeneratorClass()); и во ВьюМодели используешь через интефейсную переменную.

2021-10-01 18:43 UTC, EgorTrubnikov commented on SkillChat.Client.ViewModel/ColorGeneratorClass.cs
> +        public object GetColor(string index)
Вот здесь метод возвращает object. Почему не string. Свойство Foreground в TextBlock принимает в качестве аргумента строку из перечисления имён цветов.

2021-10-01 18:48 UTC, EgorTrubnikov commented on SkillChat.Client.ViewModel/ColorGeneratorClass.cs
> +            generator = new();
Вот здесь просто глаз зацепился за "синтаксический сахар" - почему не: generator = new ColorGenerator();

2021-10-01 18:52 UTC, EgorTrubnikov commented on SkillChat.Client.ViewModel/ColorGeneratorClass.cs
> +namespace SkillChat.Client.ViewModel
Миша, вот этот класс не должен находиться в SkillChat.Client.ViewModel, т.к. использует Авалонию. 
Это мне Паша обьяснял примерно на таком же кейсе. Ты интерфейс IColorGenerator написал в SkillChat.Client.ViewModel, а этот класс должен быть в SkillChat.Client, ты в SkillChat.Client.Programm.cs 
регистрируешь его: Locator.CurrentMutable.Register<IColorGenerator>(() => new ColorGeneratorClass()); и во ВьюМодели используешь через интефейсную переменную.

2021-10-02 07:34 UTC, KlinskiyD submitted a review, later dismissed

2021-10-02 09:49 UTC, Kibnet requested changes
Да, фича работает в основных сценариях. Но нужно исправить:
- [ ] Если выбрать сообщение для цитирования, над полем ввода сообщения отображается блок, где есть имя пользователя. Цвет там остался черным, нужно тоже раскрасить.
- [ ] Когда я делал коммит с прототипом, там было правильно разнесено по проектам, ты фишку не понял и всё засунул во вьюмодель, надо поправить, чтобы авалонии и следа не было там.
- [ ] Некоторые выбранные цвета кажутся слишком светлыми для белого фона. Надо заменить.

2021-10-02 09:49 UTC, Kibnet commented on SkillChat.Client.ViewModel/ColorGeneratorClass.cs
> +    public class ColorGeneratorClass : IColorGenerator
Слово Class в названии класса не нужно
```suggestion
    public class ColorGenerator : IColorGenerator
```

2021-10-02 09:49 UTC, Kibnet commented on SkillChat.Client.ViewModel/ColorGeneratorClass.cs
> +        public object GetColor(string index)
Хороший вопрос. Но наверно чтобы можно было передавать и не именованные цвета, так как тип возвращаемого значения не string а SolidColorBrush. Тут норм, но сам этот класс должен быть в клиенте, а не во вьюмодели.

2021-10-02 09:49 UTC, Kibnet commented on SkillChat.Client.ViewModel/ColorGetter.cs
> +        };
Тут пока можно так оставить, если будем делать темы, то тут будет подгружаться другой список цветов, которые посветлее.

2021-10-02 09:49 UTC, Kibnet commented on SkillChat.Client.ViewModel/ColorGetter.cs
> +            var user = users.FirstOrDefault(u => u.UserID == userId);
Это неоптимально проходить по списку для поиска пользователя, нужно просто использовать словарь с ключём UserID

2021-10-02 09:49 UTC, Kibnet commented on SkillChat.Client.ViewModel/SkillChat.Client.ViewModel.csproj
> +        <TargetFramework>net5.0</TargetFramework>
А это зачем???? Чем тебе нетстандарт не угодил?

2021-10-02 09:49 UTC, Kibnet commented on SkillChat.Client.ViewModel/MessageViewModel.cs
> +            color = new ColorGetter();
Создавать для каждого сообщения свой геттер не имеет смысла. Должен быть общий для всех.

2021-10-02 09:49 UTC, Kibnet commented on SkillChat.Client.ViewModel/ColorGetter.cs
> +        private static List<UserSeanceColor> users = new List<UserSeanceColor>();
Использование статического списка для множества экземпляров класса очень плохая идея, список не потокобезопасный, могут быть проблемы.

2021-10-02 09:49 UTC, Kibnet commented on SkillChat.Client.ViewModel/MessageViewModel.cs
> +        ColorGetter color;
Это свойство тут явно лишнее

2021-10-02 09:49 UTC, Kibnet commented on SkillChat.Client.ViewModel/SkillChat.Client.ViewModel.csproj
> +        <PackageReference Include="AvaloniaColorGenerator" Version="1.0.0" />
Этого тут быть не должно. Оно должно быть только в Client, и оно там уже есть.

2021-10-02 09:49 UTC, Kibnet commented on SkillChat.Client.ViewModel/UserSeanceColor.cs
> +    }
Этот класс вообще не нужен, если использовать словарь

2021-10-02 09:49 UTC, Kibnet commented on SkillChat.Client/Program.cs
> +using Avalonia.Media;
Эти юзинги тут не нужны

2021-10-02 09:49 UTC, Kibnet commented on SkillChat.Client/Views/Messages.xaml
> +                        Foreground="{Binding NameColorBrush}"
Логичнее было бы назвать свойство ForegroundBrush
```suggestion
                        Foreground="{Binding ForegroundBrush}"
```

2021-10-02 09:49 UTC, Kibnet commented on SkillChat.Client/Views/Profile/Settings.xaml
> +                        Margin="0 50"
Как это относится к задаче?

2021-10-02 09:49 UTC, Kibnet commented on SkillChat.Client/Views/QuotedMessage.axaml
> +                    Foreground="{Binding NameColorBrush}"/>
Логичнее было бы назвать свойство ForegroundBrush
```suggestion
                    Foreground="{Binding ForegroundBrush}"/>
```

2021-10-04 10:41 UTC, UnluckyD commented on SkillChat.Client.ViewModel/ColorGeneratorClass.cs
> +            generator = new();
Resharper сам так автокодит :)

2021-10-04 23:22 UTC, Kibnet requested changes
Я понял что мы пошли неправильным путём. Нужно сделать конвертер, который на входе будет получать через биндинг идентификатор пользователя, а в разметку возвращать цвет. Большая часть проблем сама уйдёт при таком подходе. Соответсвенно текущий код надо переместить в конвертер.

2021-10-04 23:22 UTC, Kibnet commented on SkillChat.Client.ViewModel/ColorGetter.cs
> +    }
Я думаю что всю эту логику нужно вынести в реализацию IColorGenerator, чтобы вьюмодель ничего не знала о том у кого какой цвет. Плюс при переключении темы(в будущем) вьюмодель не должна это обрабатывать каким-то образом, пусть вью слой над этим работает.

2021-10-04 23:22 UTC, Kibnet commented on SkillChat.Client.ViewModel/Interfaces/IColorGenerator.cs
> +        object GetColor(string colorName);
Этот метод должен получать не название цвета, а UserId, и всю работу по выбору цвета и его прикреплению к пользователю пусть делает реализация этого метода.
```suggestion
        object GetColor(string userId);
```

2021-10-04 23:22 UTC, Kibnet commented on SkillChat.Client.ViewModel/ColorGetter.cs
> +            }
Чтобы не лохануться тут нужно использовать синхронизацию через конструкцию lock. Чтобы избежать ситуацию когда этот код вызывается одновременно для двух сообщений разных пользователей и им выдался один цвет.

2021-10-04 23:22 UTC, Kibnet commented on SkillChat.Client.ViewModel/ColorGetter.cs
> +        private Dictionary<string,object> users = new ();
Для работы в многопоточке лучше использовать [ConcurrentDictionary<TKey,TValue>](https://docs.microsoft.com/ru-ru/dotnet/api/system.collections.concurrent.concurrentdictionary-2?view=netcore-3.1)
```suggestion
        private ConcurrentDictionary<string,object> users = new ();
```

2021-10-04 23:22 UTC, Kibnet commented on SkillChat.Client.ViewModel/MessageViewModel.cs
> +        private static ColorGetter color = new ();
Нафиг выкини статическое свойство. Статику обычно можно заменить более удобными конструкциями, и использовать надо действительно только там где она удобна и не снижает других качеств кода. В частности статика делает код абсолютно нетестируемым через автотесты.
Чаще всего это признак того, что код плохо спроектирован.
```suggestion
```

2021-10-05 14:58 UTC, KlinskiyDD approved these changes

2021-10-06 09:34 UTC, Mileeena submitted a review, later dismissed

2021-10-06 21:38 UTC, Kibnet commented on SkillChat.Client/Utils/UserIdToBrushConverter.cs
> +        private object o = new();
Для синхронизации не годится, так как в коде создаётся 3 раза в 3 вьюхах. Нужно хотя бы сделать статическим.

2021-10-06 21:39 UTC, Kibnet commented on SkillChat.Client/Utils/UserIdToBrushConverter.cs
> +            if (value != null)
Если значение будет null, то упадёт на 38 строке при попытке получить из словаря. Нужно правильно обработать else

2021-10-06 21:41 UTC, Kibnet commented on SkillChat.Client/Utils/UserIdToBrushConverter.cs
> +                if(!users.ContainsKey((string)value))
Приведение к стрингу надо делать безопасным через as, иначе упадет если передать что-то другое

2021-10-06 21:44 UTC, Kibnet commented on SkillChat.Client/Utils/UserIdToBrushConverter.cs
> +                        users.GetOrAdd((string) value, Color.Parse(hex));
Тут происходит повторное приведение к стрингу, нужно сделать один раз выше и использовать переменную

2021-10-06 21:46 UTC, Kibnet commented on SkillChat.Client/Utils/UserIdToBrushConverter.cs
> +            return new SolidColorBrush(users[(string)value]);
В случае когда мы только что добавили в словарь, глупо лезть за ним, нужно использовать локальную переменную.

2021-10-06 21:46 UTC, Kibnet commented on SkillChat.Client/Utils/UserIdToBrushConverter.cs
> +        private static ConcurrentDictionary<string, Color> users = new();
Почему бы тут сразу не хранить SolidColorBrush вместо Color?

2021-12-08 19:35 UTC, Kibnet approved these changes

2021-12-08 19:36 UTC, merged