Добавил автоматическую прокрутку вниз
SkillChat/SkillChat pull request #109
Opened 2021-09-30 08:17 UTC by KlinskiyDD

Прокрутка работает, только для пользователя, который отправил сообщение.

2021-09-30 08:27 UTC, EgorTrubnikov submitted a review, later dismissed

2021-09-30 08:29 UTC, UnluckyD submitted a review, later dismissed

2021-09-30 10:38 UTC, UnluckyD submitted a review, later dismissed

2021-09-30 14:34 UTC, Mileeena requested changes
Если отвечать на большое сообщение (в котором много файлов или много строк), то все ломается

2021-09-30 14:41 UTC, Mileeena commented
> Если отвечать на большое сообщение (в котором много файлов или много строк), то все ломается

upd: это исправлено в другой ветке уже

2021-09-30 14:41 UTC, Mileeena submitted a review, later dismissed

2021-10-01 22:13 UTC, Kibnet requested changes
Да, ты решил проблему автоскролла для своих сообщений. Но если пока ты пишешь сообщение тебе пришлют сообщение другие пользователи в чат, то ты их не увидишь пока не отправишь своё. Это надо поправить.

2021-10-13 07:35 UTC, merged