fix/#114-Displaying-the-user-name-in-the-title
SkillChat/SkillChat pull request #115
Opened 2021-10-04 12:54 UTC by Mileeena

2021-10-04 15:49 UTC, UnluckyD approved these changes

2021-10-04 17:41 UTC, EgorTrubnikov approved these changes

2021-10-05 21:21 UTC, Kibnet submitted a review, later dismissed
Отличная работа! Нашёл один момент, который тоже можно поправить, при изменении имени в профиле, можно тоже обновлять и заголовок.

2021-10-06 09:28 UTC, Mileeena commented
> Отличная работа! Нашёл один момент, который тоже можно поправить, при изменении имени в профиле, можно тоже обновлять и заголовок.

Сделано

2021-10-06 09:38 UTC, UnluckyD approved these changes

2021-10-06 18:20 UTC, EgorTrubnikov approved these changes

2021-10-06 22:55 UTC, Kibnet requested changes
Нужно доработать.

2021-10-06 22:55 UTC, Kibnet commented on SkillChat.Client.ViewModel/MainWindowViewModel.cs
> +                                    User.UserName = string.IsNullOrEmpty(data.UserName.Trim()) ? data.UserLogin : data.UserName;
Падает если data.UserName = null

2021-10-06 22:55 UTC, Kibnet commented on SkillChat.Client.ViewModel/MainWindowViewModel.cs
> +                                    Title = IsSignedIn ? $"SkillChat - {User.UserName} [{ChatName}]" : $"SkillChat";
Почему тут не использовать User.DisplayName? Если такого нет, то нужно добавить.

2021-10-06 22:55 UTC, Kibnet commented on SkillChat.Client.ViewModel/ProfileViewModel.cs
> +            DisplayName = string.IsNullOrEmpty(profile.DisplayName.Trim()) ? profile.Login : profile.DisplayName;
Кажется абсолютно неправильно подставлять сюда логин если на самом деле пусто

2021-10-07 00:46 UTC, Mileeena commented on SkillChat.Client.ViewModel/MainWindowViewModel.cs
> +                                    User.UserName = string.IsNullOrEmpty(data.UserName.Trim()) ? data.UserLogin : data.UserName;
Добавил проверку

2021-10-07 00:46 UTC, Mileeena commented on SkillChat.Client.ViewModel/MainWindowViewModel.cs
> +                                    Title = IsSignedIn ? $"SkillChat - {User.UserName} [{ChatName}]" : $"SkillChat";
Добавил

2021-10-07 08:22 UTC, Kibnet commented on SkillChat.Client.ViewModel/MainWindowViewModel.cs
> +                                    User.UserName = string.IsNullOrEmpty(data.UserName.Trim()) ? data.UserLogin : data.UserName;
Нужно было просто добавить знак вопроса

2021-10-07 08:25 UTC, Kibnet commented on SkillChat.Client.ViewModel/CurrentUserViewModel.cs
> +        public string DisplayName { get; set; }
Нужно сделать вычислимым, чтобы не дублировать логику везде где меняются зависимые свойства

2021-10-07 08:28 UTC, Kibnet commented on SkillChat.Client.ViewModel/MainWindowViewModel.cs
> +                                    }
Это всё можно вынести в вычислимое свойство. И ты по сути два раза проверяешь на равенство null через !=null  и IsNullOrEmpty. Можно было просто добавить ? перед .Trim()

2021-10-07 08:29 UTC, Kibnet commented on SkillChat.Client.ViewModel/MainWindowViewModel.cs
> +                                    Title = IsSignedIn ? $"SkillChat - {User.DisplayName} [{ChatName}]" : $"SkillChat";
Это поле было вычислимым, зачем вынес и закопипастил?

2021-10-07 08:29 UTC, Kibnet commented on SkillChat.Client.ViewModel/MainWindowViewModel.cs
> +        public string Title { get; set; }
Верни как было. Зачем убрал?

2021-10-07 14:41 UTC, Mileeena commented on SkillChat.Client.ViewModel/MainWindowViewModel.cs
> +        public string Title { get; set; }
Переделал

2021-10-10 18:38 UTC, Kibnet approved these changes
Хорошая работа!

2021-10-10 18:38 UTC, merged