Добавлена возможность изменения имени пользователя и оповещение оста…
SkillChat/SkillChat pull request #24
Opened 2021-03-23 10:01 UTC by tranee95

Добавлена возможность изменения имени пользователя и оповещение остальных об этом

2021-03-23 14:13 UTC, Mileeena submitted a review, later dismissed
По коду вопросов нет.

2021-03-23 20:12 UTC, Kibnet requested changes
Функциональность нарушена, будет падать. Нужно исправить.

2021-03-23 20:12 UTC, Kibnet commented on SkillChat.Client.ViewModel/MainWindowViewModel.cs
> +                            .First();
А если сообщений не найдётся? Лучше передавать старое имя вместе с новым.

2021-03-23 20:12 UTC, Kibnet commented on SkillChat.Client.ViewModel/MainWindowViewModel.cs
> +                        if (!User.Id.Equals(user.Id) && !string.IsNullOrEmpty(oldUserDispalyName))
Почему в половине случаев для сравнения идентификаторов используются == а в другой Equals? Надо чтобы было однообразно. Лучше везде использовать ==

2021-03-23 20:12 UTC, Kibnet commented on SkillChat.Client.ViewModel/MainWindowViewModel.cs
> +                            Messages.Add(container);
А в чём смысл этого сообщения? Если пользователь будет в 1000 чатов, во все будет транслировано что он поменял имя. А нафига?

2021-03-23 20:12 UTC, Kibnet commented on SkillChat.Client.ViewModel/MainWindowViewModel.cs
> +                            Notify.NewMessage(changeMessage.UserNickname, changeMessage.Text.Replace("\r\n", " "));
Нотификацию выводить по этому поводу тоже не имеет смысла. Только раздражать будет.

2021-03-23 20:12 UTC, Kibnet commented on SkillChat.Client.ViewModel/ProfileViewModel.cs
> +            }
А зачем это делать тут, если можно генерировать событие в методе изменения имени на сервере.

2021-03-27 04:09 UTC, Mileeena commented
1) Перестали приходить уведомления о смене имени
2) Приложение падает, если нажать на имя собеседника

2021-03-30 02:52 UTC, tranee95 commented
по этому пункту "Перестали приходить уведомления о смене имени"
решили убрать этот функционал так как будет только мешаться

2021-03-30 13:06 UTC, Mileeena commented
1) При смене имени выкидывает в окно регистрации всех, кроме того кто сменил имя.

2021-04-01 14:58 UTC, Mileeena approved these changes
Приложение работает стабильно, смена имени происходит везде разом, все баги были исправлены.

2021-04-01 15:05 UTC, Mileeena approved these changes
Приложение работает стабильно, смена имени происходит везде разом, все баги были исправлены.

2021-04-09 04:05 UTC, Kibnet requested changes

2021-04-09 04:05 UTC, Kibnet commented on SkillChat.Client.ViewModel/ProfileViewModel.cs
> +                await _hub.UpdateUserDisplayName(Profile.DisplayName, Profile.Id);
Логичнее назвать UpdateMyDisplayName. Profile.Id передавать не нужно, так как сервер и так знает кто вызывает метод. Можно убрать из списка параметров.

2021-04-15 13:45 UTC, Dimaboxx approved these changes

2021-04-15 13:54 UTC, Dimaboxx submitted a review, later dismissed

2021-04-25 19:30 UTC, merged