Auto scroll
SkillChat/SkillChat pull request #27
Opened 2021-04-06 05:48 UTC by Dimaboxx

2021-04-13 09:36 UTC, tranee95 approved these changes
Вроде все окей)

2021-04-15 22:33 UTC, Kibnet requested changes
В целом код рабочий, это радует!
По использованию рефлексии есть рекомендации. Можно сделать элегантнее.

2021-04-15 22:33 UTC, Kibnet commented on SkillChat.Client/Views/MainWindow.xaml.cs
> +                var verticaloffsetmax = (double)prop.GetValue(MessagesScroller);
1. Переиспользовать переменную для разных данных, затея плохая, экономии нет, а путаницу в код вносит.
2. Если используешь рефлексию, надо осознавать что она дорогая. Поэтому извлечение нужных свойст надо делать один раз, у тебя же класс не меняется во время работы. А потом только извлекать значения, это будет значительно быстрее.
3. Ты невнимательно смотрел исходники ScrollViewer, а если вообще не смотрел, то это большое упущение. Потому что есть способ извлечения нужных свойств без рефлексии, например через статическое свойство ScrollViewer.VerticalScrollBarValueProperty, такое же есть и для второго.

2021-04-15 22:33 UTC, Kibnet commented on SkillChat.Client/Views/MainWindow.xaml.cs
>  		private void ScrollToEndMethod(object sender, AvaloniaPropertyChangedEventArgs e)
Описание метода стоит актуализировать, так как логика поменялась, чтобы не вводить в заблуждение читающих. Может быть стоит поменять и название метода на более подходящий.

2021-04-16 11:13 UTC, Dimaboxx commented on SkillChat.Client/Views/MainWindow.xaml.cs
> +                var verticaloffsetmax = (double)prop.GetValue(MessagesScroller);
посмотрел. переделал.

2021-04-16 11:14 UTC, Dimaboxx commented on SkillChat.Client/Views/MainWindow.xaml.cs
>  		private void ScrollToEndMethod(object sender, AvaloniaPropertyChangedEventArgs e)
изменил но не уверен что лучше стало

2021-04-16 11:47 UTC, Kibnet approved these changes
Теперь всё отлично!

2021-04-20 08:32 UTC, Kibnet approved these changes

2021-04-20 08:32 UTC, merged