Отправка файлов и кнопка файла
SkillChat/SkillChat pull request #43
Opened 2021-05-26 20:30 UTC by tranee95

2021-05-28 05:23 UTC, Kozlov-AE approved these changes
В целом вроде все ок)

2021-05-28 05:23 UTC, Kozlov-AE commented on SkillChat.Client/Views/AttachmentView.axaml
> +<UserControl
Смени расширение файла на xaml

2021-05-28 05:23 UTC, Kozlov-AE commented on SkillChat.Client/Views/AttachmentView.axaml.cs
> +using Avalonia.Controls;
Смени расширение на XAML

2021-05-28 05:23 UTC, Kozlov-AE commented on SkillChat.Interface/IAttachment.cs
> +    public interface IAttachment
название как у модели, описание как у сервиса. Для моделей не надо делать интерфейсы.

2021-05-28 05:23 UTC, Kozlov-AE commented on SkillChat.Interface/ReceiveMessage.cs
> +        public List<Attachment> Attachments { get; set; }
Ну уж если определил интерфейс, то почему здесь реализация?

2021-05-28 05:23 UTC, Kozlov-AE commented on SkillChat.Server.ServiceModel/Extensions/ByteExtension.cs
> +        public static string SizeCalculating(this byte[] bytes)
У FileInfo есть Lenght, может его стоило заюзать, а потом уже преобразовывать длину в байтах в обозначения? А то он на каждый вызов вычисляет длину массива.

2021-05-29 18:28 UTC, Kozlov-AE approved these changes

2021-05-30 23:06 UTC, Kibnet requested changes
Очень много замечаний. 
1. Файлы надо хранить в отдельных документах а не в сообщениях
2. Везде в коде файлы всегда вычитываются в память полностью, причём тебя не смутило что везде нужно передавать потоки, а не массивы.
3. Нарушения границ слоёв в появлении недопустимых ссылок между проектами
4. Мусорные изменения(форматирование в неиспользуемых файлах, добавление ненужных юзингов)
5. Не используется автомаппинг моделей, просто заюзана одна модель во всех слоях сразу. Для каждого слоя должна быть своя.

Подробнее в комментариях в коде

2021-05-30 23:06 UTC, Kibnet commented on SkillChat.Client.ViewModel/AttachmentViewModel.cs
> +                    var stream = new MemoryStream(File.ReadAllBytes(s));
В UploadFile не просто так просят Stream. Это для того чтобы не загружать весь файл в оперативку в один момент времени. Нужно открыть файл для потокового чтения и передать стрим.

2021-05-31 21:35 UTC, tranee95 commented on SkillChat.Client/Views/AttachmentView.axaml
> +<UserControl
сделано

2021-05-31 21:35 UTC, tranee95 commented on SkillChat.Client/Views/AttachmentView.axaml.cs
> +using Avalonia.Controls;
сделано

2021-05-31 21:35 UTC, tranee95 commented on SkillChat.Interface/IAttachment.cs
> +    public interface IAttachment
удалил интерфейс

2021-05-31 21:36 UTC, tranee95 commented on SkillChat.Server.ServiceModel/Extensions/ByteExtension.cs
> +        public static string SizeCalculating(this byte[] bytes)
сделано

2021-05-31 21:36 UTC, tranee95 commented on SkillChat.Server.ServiceModel/Extensions/ByteExtension.cs
> +            else result = $"{kb:0.00} КБ";
сделано

2021-05-31 21:37 UTC, tranee95 commented on SkillChat.Server.ServiceModel/Molds/Files/AttachmentMold.cs
> +        [Description("Id Отрпавителя")]
сделано

2021-05-31 21:41 UTC, tranee95 commented on SkillChat.Server.ServiceInterface/FilesService.cs
> +    public class FilesService : Service
готова

2021-05-31 21:43 UTC, tranee95 commented on SkillChat.Server.ServiceModel/Attachment.cs
> +        public string ChatId { get; set; }
готова

2021-05-31 21:43 UTC, tranee95 commented on SkillChat.Server/appsettings.json
> +    "Path": "D:\\SkillChat"
готова

2021-05-31 21:46 UTC, tranee95 commented on SkillChat.Server.ServiceModel/Attachment.cs
> +        public string SenderId { get; set; }
готова

2021-05-31 21:58 UTC, tranee95 commented on SkillChat.Server.ServiceModel/Attachment.cs
> +    [Route("/setAttachment", "POST", Summary = "Отправка файла на сервер", Notes = "Отправка файла на сервер")]
готова

2021-05-31 21:58 UTC, tranee95 commented on SkillChat.Server.ServiceModel/Attachment.cs
> +    [Route("/getAttachment", "POST", Summary = "Получение файла с сервер", Notes = "Получение файла с сервер")]
готова

2021-05-31 21:58 UTC, tranee95 commented on SkillChat.Server.ServiceInterface/FilesService.cs
> +            var dirPatch = Configuration["FileDir:Path"] ?? "C:\\SkillChat";
готова

2021-05-31 21:58 UTC, tranee95 commented on SkillChat.Server.ServiceInterface/FilesService.cs
> +            var dirPatch = Configuration["FileDir:Path"] ?? "C:\\SkillChat";
готова

2021-05-31 22:01 UTC, tranee95 commented on SkillChat.Client/SkillChat.Client.csproj
> +    </ItemGroup>
готова

2021-05-31 22:01 UTC, tranee95 commented on SkillChat.Client/SkillChat.Client.csproj
> +    </ItemGroup>
готова

2021-05-31 22:01 UTC, tranee95 commented on SkillChat.Client/App.xaml
> +        <StyleInclude Source="/Styles/SendMessageStyle.xaml" />
готова

2021-05-31 22:02 UTC, tranee95 commented on SkillChat.Client.ViewModel/AttachmentViewModel.cs
> +            var attachment = await _serviceClient.PostAsync<byte[]>("/getAttachment", new { Id = data.FileId });
готова

2021-05-31 22:02 UTC, tranee95 commented on SkillChat.Client.ViewModel/AttachmentViewModel.cs
> +                _serviceClient.PostFilesWithRequest<List<Attachment>>("/setAttachment", response, uploadFile);
готова

2021-06-01 15:22 UTC, tranee95 commented on SkillChat.Server.ServiceInterface/FilesService.cs
> +        public IMapper Mapper { get; set; }
готова

2021-06-01 15:24 UTC, tranee95 commented on SkillChat.Server.ServiceModel/Attachment.cs
> +    public class SetAttachment : IReturn<List<Attachment>>
готова

2021-06-01 15:26 UTC, tranee95 commented on SkillChat.Server/Hubs/ChatHub.cs
> +                Attachments = hubMessage.Attachment
готова

2021-06-01 15:26 UTC, tranee95 commented on SkillChat.Server.Domain/Message.cs
> +        public List<Attachment> Attachments { get; set; }
готова

2021-06-01 15:27 UTC, tranee95 commented on SkillChat.Server.ServiceModel/Molds/MessageMold.cs
> +        public List<Attachment> Attachments { get; set; }
готова

2021-06-01 15:27 UTC, tranee95 commented on SkillChat.Server.ServiceModel/Molds/Files/Attachment.cs
> +        public string SizeName { get; set; }
готова

2021-06-01 15:27 UTC, tranee95 commented on SkillChat.Server.ServiceModel/Molds/Files/Attachment.cs
> +        public string Extensions { get; set; }
готова

2021-06-01 15:27 UTC, tranee95 commented on SkillChat.Server.ServiceModel/Molds/Files/Attachment.cs
> +        public DateTime UpladDateTime { get; set; }
готова

2021-06-01 15:28 UTC, tranee95 commented on SkillChat.Server.ServiceInterface/FilesService.cs
> +                var bytes = file.InputStream.ToBytes();
готова

2021-06-01 15:29 UTC, tranee95 commented on SkillChat.Server.ServiceInterface/SkillChat.Server.ServiceInterface.csproj
> +        <PackageReference Include="SignalR.EasyUse.Server" Version="0.2.1" />
готова

2021-06-01 15:29 UTC, tranee95 commented on SkillChat.Server.ServiceInterface/ChatService.cs
> +        public IConfiguration Configuration { get; set; }
готова

2021-06-01 15:30 UTC, tranee95 commented on SkillChat.Server.Domain/SkillChat.Server.Domain.csproj
> +      <ProjectReference Include="..\SkillChat.Server.ServiceModel\SkillChat.Server.ServiceModel.csproj" />
готова

2021-06-01 15:38 UTC, tranee95 commented on SkillChat.Server.ServiceModel/Molds/Files/Attachment.cs
> +    public class Attachment
готова

2021-06-01 16:08 UTC, tranee95 commented on SkillChat.Interface/HubMessage.cs
> +        public List<Attachment> Attachment { get; set; }
готов

2021-06-01 16:08 UTC, tranee95 commented on SkillChat.Interface/SkillChat.Interface.csproj
> +      <ProjectReference Include="..\SkillChat.Server.ServiceModel\SkillChat.Server.ServiceModel.csproj" />
готова

2021-06-02 21:26 UTC, Kibnet commented on SkillChat.Server.ServiceModel/Attachment.cs
> +    [Route("/getAttachment", "POST", Summary = "Получение файла с сервер", Notes = "Получение файла с сервер")]
Недоделал. Забыл {id} в путь добавить

2021-06-07 10:59 UTC, Kibnet requested changes
Очередная порция критических комментов. Все подлежат исправлению.

2021-06-07 10:59 UTC, Kibnet commented on .gitignore
> +SkillChat.Server/temp
В конфиге два пути, а тут только один

2021-06-07 10:59 UTC, Kibnet commented on SkillChat.Client.ViewModel/AttachmentViewModel.cs
> +    public class AttachmentViewModel
Логичнее было бы назвать SendAttachmentsViewModel

2021-06-07 10:59 UTC, Kibnet commented on SkillChat.Client.ViewModel/AttachmentViewModel.cs
> +        public List<AttachmentMold> Attachments { get; set; }
Использовать модели сервера во вьюмодели нельзя, нужно создать соответсвующие вьюмодели и маппить

2021-06-07 10:59 UTC, Kibnet commented on SkillChat.Client.ViewModel/AttachmentViewModel.cs
> +        private string[] AttachmentsPath { get; set; }
Хранить эти данные не нужно, можно превратить в локальную переменную. Используется только в методе Open

2021-06-07 10:59 UTC, Kibnet commented on SkillChat.Client.ViewModel/AttachmentViewModel.cs
> +        public async Task Open(string[] attachments)
На вход лучше получать IEnumerable<string>

2021-06-07 10:59 UTC, Kibnet commented on SkillChat.Client.ViewModel/AttachmentViewModel.cs
> +            AttachmentsPath = attachments;
Пути надо преобразовывать через ToList()

2021-06-07 10:59 UTC, Kibnet commented on SkillChat.Client.ViewModel/AttachmentViewModel.cs
> +                await using (var stream = File.OpenRead(path))
Открывать файл вовсе не нужно на данном этапе. Тебе нужно взять только размер, он есть в FileInfo

2021-06-07 10:59 UTC, Kibnet commented on SkillChat.Client.ViewModel/AttachmentViewModel.cs
> +                        })
Так и напрашивается использование маппера

2021-06-07 10:59 UTC, Kibnet commented on SkillChat.Client.ViewModel/AttachmentViewModel.cs
> +                    var savePath = $"{settings?.AttachmentDefaultPath}\\{data.FileName}";
Собирать путь надо через Path.Combine

2021-06-07 10:59 UTC, Kibnet commented on SkillChat.Client.ViewModel/AttachmentViewModel.cs
> +        public async Task Download(AttachmentMold data)
Этот метод не должен быть тут, логичнее поместить его в AttachmentMessageViewModel

2021-06-07 10:59 UTC, Kibnet commented on SkillChat.Client.ViewModel/AttachmentViewModel.cs
> +                            var bytesInStream = new byte[attachment.Length];
Размер буффера должен быть не более 4 Мб

2021-06-07 10:59 UTC, Kibnet commented on SkillChat.Client.ViewModel/AttachmentViewModel.cs
> +                        Notification.Manager.Show("Файл сохранён", $"Файл {data.FileName} был сохранён {Path.GetDirectoryName(savePath)}");
Вместо вывода нотификации, надо менять внешний вид самого файла в чате, вместо "загрузить" должно стать "открыть"

2021-06-07 20:17 UTC, tranee95 commented on SkillChat.Server/appsettings.json
> +    "DownloadPath": "Download\\Attachment"
в файле appsettings.json настройки которые используются только в SkillChat.Server.ServiceInterface проекте

2021-06-07 20:17 UTC, tranee95 commented on SkillChat.Server/appsettings.json
> +    "Path": "temp\\Attachment",
поправил

2021-06-07 20:18 UTC, tranee95 commented on SkillChat.Server/Properties/launchSettings.json
> -      }
готова

2021-06-07 20:22 UTC, tranee95 commented on SkillChat.Server/appsettings.json
> +    "DownloadPath": "Download\\Attachment"
в файле appsettings.json настройки которые используются только в SkillChat.Server.ServiceInterface проекте

2021-06-07 20:22 UTC, tranee95 commented on SkillChat.Server/appsettings.json
> +    "Path": "temp\\Attachment",
готова

2021-06-07 20:23 UTC, tranee95 commented on SkillChat.Server/Properties/launchSettings.json
> -      }
готова

2021-06-07 20:25 UTC, tranee95 commented on SkillChat.Server/AppModelMapping.cs
> +                .ForMember(m => m.SizeName, e => e.Ignore());
готова

2021-06-07 21:20 UTC, tranee95 commented on SkillChat.Server.ServiceModel/Molds/Attachment/AttachmentMold.cs
> +        public string Extensions { get; set; }
готова

2021-06-07 21:21 UTC, tranee95 commented on SkillChat.Server.ServiceModel/Molds/Attachment/AttachmentMold.cs
> +        [Description("Id Отрпавителя")]
готова

2021-06-07 21:29 UTC, tranee95 commented on SkillChat.Server.ServiceModel/Extensions/ByteExtension.cs
> +                size /= 1024;
готова

2021-06-07 21:30 UTC, tranee95 commented on SkillChat.Server.ServiceModel/Chat.cs
> +    public class GetChatsList : IReturn<ChatPage>
откатил

2021-06-07 21:37 UTC, tranee95 commented on SkillChat.Server.ServiceModel/Attachment.cs
> +    [Route("/attachments", "GET", Summary = "Получение файла с сервер", Notes = "Получение файла с сервер")]
готова

2021-06-07 21:38 UTC, tranee95 commented on SkillChat.Server.ServiceModel/Attachment.cs
> +    [Route("/attachments", "GET", Summary = "Получение файла с сервер", Notes = "Получение файла с сервер")]
готова

2021-06-07 21:39 UTC, tranee95 commented on SkillChat.Server.ServiceInterface/SkillChat.Server.ServiceInterface.csproj
> +      <ProjectReference Include="..\SkillChat.Server.ServiceModel\SkillChat.Server.ServiceModel.csproj" />
вернул

2021-06-07 21:39 UTC, tranee95 commented on SkillChat.Server.ServiceInterface/ChatService.cs
> +
убрал

2021-06-07 21:39 UTC, tranee95 commented on SkillChat.Server.ServiceInterface/AttachmentService.cs
> +            var dirPatch = Configuration["FileDir:Path"] ?? Configuration["FileDir:DownloadPath"];
убрал

2021-06-07 21:47 UTC, tranee95 commented on SkillChat.Server.ServiceInterface/AttachmentService.cs
> +            await using (var fileStream = File.Create($"{dirPatch}/{fileId}", (int)stream.Length))
готова

2021-06-07 21:54 UTC, tranee95 commented on SkillChat.Server.ServiceInterface/AttachmentService.cs
> +                Directory.CreateDirectory(dirPatch);
готова

2021-06-07 23:48 UTC, tranee95 commented on SkillChat.Server.ServiceInterface/AttachmentService.cs
> +                var bytesInStream = new byte[stream.Length];
готова

2021-06-07 23:52 UTC, tranee95 commented on SkillChat.Server.ServiceInterface/AttachmentService.cs
> +            var file = Request.Files.FirstOrDefault();
готова

2021-06-07 23:53 UTC, tranee95 commented on SkillChat.Server.ServiceInterface/AttachmentService.cs
> +                Id = Guid.NewGuid().ToString(),
готова

2021-06-08 00:19 UTC, tranee95 commented on SkillChat.Server.ServiceInterface/AttachmentService.cs
> +            return File.OpenRead($"{dirPatch}\\{request.Id}");
готова

2021-06-08 00:19 UTC, tranee95 commented on SkillChat.Server.ServiceInterface/AttachmentService.cs
> +            var filePath = $"{dirPatch}\\{request.Id}";
готова

2021-06-08 00:20 UTC, tranee95 commented on SkillChat.Server.ServiceInterface/AttachmentService.cs
> +            var dirPatch = Configuration["FileDir:Path"] ?? Configuration["FileDir:DownloadPath"];
готова

2021-06-08 00:23 UTC, tranee95 commented on SkillChat.Server.Domain/Attachment.cs
> +        public DateTimeOffset UpladDateTime { get; set; }
готова

2021-06-08 00:25 UTC, tranee95 commented on SkillChat.Interface/SkillChat.Interface.csproj
> -
откатил

2021-06-08 00:27 UTC, tranee95 commented on SkillChat.Interface/AttachmentDisplayMold.cs
> +        public DateTimeOffset UpladDateTime { get; set; }
готова

2021-06-08 00:32 UTC, tranee95 commented on SkillChat.Interface/AttachmentDisplayMold.cs
> +        public string Extensions { get; set; }
готова

2021-06-08 00:45 UTC, tranee95 commented on SkillChat.Client.ViewModel/MessageViewModel.cs
> +        public List<AttachmentMessageViewModel> Attachment { get; set; }
готова

2021-06-08 00:46 UTC, tranee95 commented on SkillChat.Client.ViewModel/AttachmentViewModel.cs
> +    public class AttachmentViewModel
готова

2021-06-08 01:03 UTC, tranee95 commented on SkillChat.Client.ViewModel/AttachmentViewModel.cs
> +        public List<AttachmentMold> Attachments { get; set; }
готова

2021-06-08 01:04 UTC, tranee95 commented on SkillChat.Client.ViewModel/AttachmentViewModel.cs
> +        private string[] AttachmentsPath { get; set; }
готова

2021-06-08 01:09 UTC, tranee95 commented on SkillChat.Client.ViewModel/AttachmentViewModel.cs
> +        public async Task Open(string[] attachments)
готова

2021-06-08 01:10 UTC, tranee95 commented on SkillChat.Client.ViewModel/AttachmentViewModel.cs
> +            AttachmentsPath = attachments;
готова

2021-06-08 01:11 UTC, tranee95 commented on SkillChat.Client.ViewModel/AttachmentViewModel.cs
> +                await using (var stream = File.OpenRead(path))
готова

2021-06-08 01:12 UTC, tranee95 commented on SkillChat.Client.ViewModel/AttachmentViewModel.cs
> +                    var savePath = $"{settings?.AttachmentDefaultPath}\\{data.FileName}";
готова

2021-06-08 01:22 UTC, tranee95 commented on SkillChat.Client.ViewModel/AttachmentViewModel.cs
> +        public async Task Download(AttachmentMold data)
в AttachmentMessageViewModel как раз есть реализация Download

2021-06-08 01:48 UTC, tranee95 commented on SkillChat.Client.ViewModel/AttachmentViewModel.cs
> +                        Notification.Manager.Show("Файл сохранён", $"Файл {data.FileName} был сохранён {Path.GetDirectoryName(savePath)}");
готова

2021-06-08 01:48 UTC, tranee95 commented on SkillChat.Client.ViewModel/AttachmentViewModel.cs
> +                            var bytesInStream = new byte[attachment.Length];
готова

2021-06-09 10:04 UTC, tranee95 commented on SkillChat.Client.ViewModel/ChatClientSettings.cs
> +        public string AttachmentDefaultPath { get; set; }
Готова

2021-06-09 10:14 UTC, tranee95 commented on SkillChat.Client/Views/Notify.xaml
> +    <Border CornerRadius="8,0,0,8"  Background="#F2EEFF"  Width="340" Height="90">
чтобы влазило сообщение о скаченном файле

2021-06-09 17:41 UTC, tranee95 commented on SkillChat.Client.ViewModel/MainWindowViewModel.cs
> +            Locator.CurrentMutable.RegisterConstant(AttachmentViewModel);
поправил

2021-06-10 01:45 UTC, tranee95 commented on SkillChat.Server.ServiceModel/Attachment.cs
> +    [Route("/attachments", "POST", Summary = "Отправка файла на сервера", Notes = "Отправка файла на сервера")]
готова

2021-06-10 01:48 UTC, tranee95 commented on SkillChat.Client.ViewModel/SendAttachmentsViewModel.cs
> +                    Size = fileName.Length,
готова

2021-06-10 01:53 UTC, tranee95 commented on SkillChat.Server.ServiceInterface/AttachmentService.cs
> +                return fileStream.ToMd5Hash();
тут решил хранить хеш всех кусков

2021-06-12 21:56 UTC, Kibnet commented on SkillChat.Server.ServiceInterface/AttachmentService.cs
> +                return fileStream.ToMd5Hash();
А если будет 10 Гиговый файл, хэш будет тоже очень большим. В конце посчитай хэш от хэша всех кусков. Чтобы хэш у всех файлов был всегда одной длины.

2021-06-12 21:58 UTC, Kibnet commented on SkillChat.Client/Views/Notify.xaml
> +    <Border CornerRadius="8,0,0,8"  Background="#F2EEFF"  Width="340" Height="90">
Эти нотификации вообще не для этого. То что файл скачался будет видно по надписи "Открыть".  Да и в дизайне этого не было.

2021-06-12 22:04 UTC, Kibnet commented on SkillChat.Server.ServiceInterface/AttachmentService.cs
> +                Id = Guid.NewGuid().ToString(),
Нужно через слэш, как у всех остальных сущностей в БД. А у тебя через нижнее подчёркивание

2021-06-12 22:06 UTC, Kibnet commented on SkillChat.Server/appsettings.json
> +    "Path": "temp\\Attachment",
Нужна множественная форма слов, как и ресурсы

2021-06-12 22:07 UTC, Kibnet commented on SkillChat.Server/appsettings.json
> +    "DownloadPath": "Download\\Attachment"
Зачем тут лишний уровень вложенности?

2021-06-12 22:42 UTC, Kibnet requested changes
1. Проверять что файл есть, сразу при получении сообщений
2. При загрузке не пересоздавать буфер, в 2 местах
3. Размер буффера 4 Кб вместо 4 Мб
4. При загрузке выводится путь к файлу, а должно только название
5. Пройдись по всем моим замечаниям(conversation) которые не помечены как решённые(resolved)

2021-06-12 22:42 UTC, Kibnet commented on SkillChat.Server/appsettings.json
> +    "Path": "File\\Attachment"
1. Лишний уровень вложенности не нужен
2. Название каталогов должно отражать суть содержимого. Там будут лежать файлы и прикрепления. Нужны множественные формы слов.

2021-06-12 22:42 UTC, Kibnet commented on SkillChat.Server.ServiceModel/Chat.cs
> +using System.Net;
Откатить

2021-06-12 22:42 UTC, Kibnet commented on SkillChat.Server.ServiceModel/Chat.cs
> +        public int? PageSize { get; set; }
Откатить

2021-06-12 22:42 UTC, Kibnet commented on SkillChat.Server.ServiceInterface/AttachmentService.cs
> +                const int bufferSize = 4096;
Буффер в 4Кб слишком мал для современных жестких, кэш у них обычно имеет размер от 8 до 32 Мб. Предлагаю использовать 4Мб.

2021-06-12 22:42 UTC, Kibnet commented on SkillChat.Server.ServiceInterface/AttachmentService.cs
> +                    var data = new byte[bufferSize];
Буер надо создать один раз вне цикла и переиспользовать его. Это драматически повлияет на повышение производительности.

2021-06-12 22:42 UTC, Kibnet commented on SkillChat.Server.ServiceInterface/AttachmentService.cs
> +                    hashString += data.ToMd5Hash();
1. Хэш надо вычислять после считывания ))).
2. Для последнего куска в хэше будет использоваться весь буффер, а это неправильно. Лучше ограничить передаваемый массив через [Span ](https://docs.microsoft.com/ru-ru/dotnet/api/system.span-1?view=net-5.0)

2021-06-12 22:42 UTC, Kibnet commented on SkillChat.Server.ServiceInterface/AttachmentService.cs
> +            var fileId = $"attachment_{Guid.NewGuid()}";
Заменить _ на /

2021-06-12 22:42 UTC, Kibnet commented on SkillChat.Client.ViewModel/SendAttachmentsViewModel.cs
> +                    FileName = fileInfo.FullName,
Тут надо выводить только имя, а не весь путь

2021-06-12 22:42 UTC, Kibnet commented on SkillChat.Client.ViewModel/MessageViewModel.cs
> +        public AttachmentMessageViewModel(AttachmentMold attachment)
По хорошему надо сразу проверить, а не лежит ли файл в папке загрузок, чтобы лишний раз не скачивать его. При этом можно проверять только название и размер

2021-06-12 22:42 UTC, Kibnet commented on SkillChat.Client.ViewModel/MainWindowViewModel.cs
> +                            var buffer = new byte[bufferSize];
Буфер надо создать один раз вне цикла. И переиспользовать его

2021-06-12 22:42 UTC, Kibnet commented on SkillChat.Client.ViewModel/MainWindowViewModel.cs
> +                    Notification.Manager.Show("Файл сохранён", $"Файл {data.FileName} был сохранён {Path.GetDirectoryName(savePath)}");
Убрать нотификацию

2021-06-12 22:42 UTC, Kibnet commented on SkillChat.Client.ViewModel/MainWindowViewModel.cs
> +                Notification.Manager.Show("Ошибка загрузки", "Во время скачивания файла произошла ошибка");
Убрать нотификацию. Оставить //TODO вывести ошибку в будущем

2021-06-12 22:42 UTC, Kibnet commented on SkillChat.Client.ViewModel/MainWindowViewModel.cs
> +                        const int bufferSize = 4096;
Размер буфера можно увеличить

2021-06-12 22:42 UTC, Kibnet commented on .gitignore
> +SkillChat.Server/temp
Этот путь уже не актуален. 
А вот каталог загрузок клиента надо добвить

2021-06-13 19:39 UTC, tranee95 commented on SkillChat.Server/appsettings.json
> +    "Path": "temp\\Attachment",
готова

2021-06-13 19:42 UTC, tranee95 commented on SkillChat.Server.ServiceInterface/AttachmentService.cs
> +            var file = Request.Files.FirstOrDefault();
готова

2021-06-13 20:17 UTC, tranee95 commented on SkillChat.Server.ServiceInterface/AttachmentService.cs
> +                Id = Guid.NewGuid().ToString(),
Поскольку файл в бд сохраняется на диске необходимо не учитывать префикс / 
сделал обход

2021-06-13 20:17 UTC, tranee95 commented on SkillChat.Server.ServiceInterface/AttachmentService.cs
> +                Id = Guid.NewGuid().ToString(),
готова

2021-06-13 20:17 UTC, tranee95 commented on SkillChat.Server.ServiceInterface/AttachmentService.cs
> +                Hash = stream.GetHashMd5(),
готова

2021-06-13 20:22 UTC, tranee95 commented on SkillChat.Server.ServiceInterface/AttachmentService.cs
> +            return File.OpenRead($"{dirPatch}\\{request.Id}");
Вынес в конструктор, готова

2021-06-13 20:23 UTC, tranee95 commented on SkillChat.Server.ServiceInterface/AttachmentService.cs
> +            var fileId = $"attachment_{Guid.NewGuid()}";
готова

2021-06-13 20:28 UTC, tranee95 commented on SkillChat.Server/appsettings.json
> +    "Path": "File\\Attachment"
готова

2021-06-13 20:31 UTC, tranee95 commented on SkillChat.Server.ServiceModel/Chat.cs
> +using System.Net;
готова

2021-06-13 20:32 UTC, tranee95 commented on SkillChat.Server.ServiceModel/Chat.cs
> +        public int? PageSize { get; set; }
готова

2021-06-13 20:35 UTC, tranee95 commented on SkillChat.Server.ServiceInterface/AttachmentService.cs
> +                const int bufferSize = 4096;
готова

2021-06-13 20:36 UTC, tranee95 commented on SkillChat.Server.ServiceInterface/AttachmentService.cs
> +                    var data = new byte[bufferSize];
готова

2021-06-13 21:18 UTC, tranee95 commented on SkillChat.Server.ServiceInterface/AttachmentService.cs
> +                    hashString += data.ToMd5Hash();
не совсем понял как реализовать второй пункт

2021-06-13 21:20 UTC, tranee95 commented on SkillChat.Client.ViewModel/SendAttachmentsViewModel.cs
> +                    FileName = fileInfo.FullName,
готова

2021-06-13 21:20 UTC, tranee95 commented on SkillChat.Client.ViewModel/MainWindowViewModel.cs
> +                            var buffer = new byte[bufferSize];
готова

2021-06-13 21:21 UTC, tranee95 commented on SkillChat.Client.ViewModel/MainWindowViewModel.cs
> +                    Notification.Manager.Show("Файл сохранён", $"Файл {data.FileName} был сохранён {Path.GetDirectoryName(savePath)}");
готова

2021-06-13 21:21 UTC, tranee95 commented on SkillChat.Client.ViewModel/MainWindowViewModel.cs
> +                Notification.Manager.Show("Ошибка загрузки", "Во время скачивания файла произошла ошибка");
готова

2021-06-13 21:21 UTC, tranee95 commented on SkillChat.Client.ViewModel/MainWindowViewModel.cs
> +                        const int bufferSize = 4096;
готова

2021-06-16 10:19 UTC, closed without merging