Автоматизированный поиск подходящих .NET версий
SkillChat/SkillChat pull request #51
Opened 2021-07-14 16:59 UTC by UnluckyD

2021-07-17 11:21 UTC, KlinskiyDD submitted a review, later dismissed
Код отлично работает. У меня нет никаких замечаний.

2021-07-20 17:29 UTC, EgorTrubnikov approved these changes
Во время Код Ревью вопросов не возникло. Всё Ок.

2021-07-22 07:47 UTC, Kibnet requested changes

2021-07-22 07:47 UTC, Kibnet commented on SkillChat.Server/NETVersionComparison.cs
> +        public static Runtime GetBestDotNETRuntime(string cfgVersion)
Вместо cfgVersion лучше назвать targetVersion - целевая версия
```suggestion
        public static Runtime GetBestDotNETRuntime(string targetVersion)
```

2021-07-22 07:47 UTC, Kibnet commented on SkillChat.Server/NETVersionComparison.cs
> +            Runtime cfgRuntime = new Runtime() {Version = cfgVersion};
Тут тоже логичнее использовать System.Version, чтобы сравнивать с целевой.
```suggestion
            var cfgRuntime = new Version(cfgVersion);
```

2021-07-22 07:47 UTC, Kibnet commented on SkillChat.Server/NETVersionComparison.cs
> +            GetPackageList(_runtimesInstaled);
Это плохая практика через параметр передавать список, который будешь заполнять, при этом метод ничего не возвращает. 
1. Выглядит так, будто метод ничего не должен возвращать, хотя название намекает на это
2. Тебе приходится инициализировать список снаружи вызова
3. При вызове этого метода больше одного раза, заполнится несколько раз.
4. Если тебе надо что-то вернуть, то используй возвращаемое значение. Если надо асинхронно, можно сделать асинхронный метод. Можно возвращать поэлементно если тип возвращаемого значения выбрать IEnumerable
```suggestion
            _runtimesInstaled = GetPackageList();
```

2021-07-22 07:47 UTC, Kibnet commented on SkillChat.Server/NETVersionComparison.cs
> +            }
Вместо этой конструкции можно было использовать Linq метод для фильтрации - Where

```suggestion
            _NETCoreRuntimes = _runtimesInstaled.Where(runtime => runtime.Name == "Microsoft.NETCore.App").ToList();
```

2021-07-22 07:47 UTC, Kibnet commented on SkillChat.Server/NETVersionComparison.cs
> +    public class NETVersionComparison
Название класса намекает на то что он реализует какой то интерфейс сравнения типа таких
![image](https://user-images.githubusercontent.com/6534396/126604243-ce2bfc2d-d866-49e4-8653-bc5deac3bd2a.png)
А по факту нет. Он получает список установленных версий и ищет подходящую версию. Лучше назвать DotNetVersionHelper
```suggestion
    public class DotNetVersionHelper
```

2021-07-22 07:47 UTC, Kibnet commented on SkillChat.Server/NETVersionComparison.cs
> +        public static Runtime GetBestDotNETRuntime(string cfgVersion)
Сам метод получения лучше не делать статическим, чтобы можно было замокать в тестах. Весь же класс нужно регистрировать через IoC как и другие. Тогда для тестов достаточно будет выделить интерфейс, когда понадобится.

2021-07-22 07:47 UTC, Kibnet commented on SkillChat.Server/NETVersionComparison.cs
> +                });
Сортировщик будет неправильно работать для версий с разным количеством символов, 
например 5.0.2, 5.0.7 и 5.0.10 отсортируются в таком порядке: 5.0.10, 5.0.2, 5.0.7
Проблема в том что ты сортируешь строки, а надо каждый элемент версии учитывать отдельно. 
System.Version умеет это из коробки

2021-07-22 07:47 UTC, Kibnet commented on SkillChat.Server/NETVersionComparison.cs
> +                foreach (var VARIABLE in _NETCoreRuntimes)
Название VARIABLE неинформативное и нарушает конвенцию именования тем, что оно большими буквами.
Должно быть что-то типа runtime
```suggestion
                foreach (var runtime in _NETCoreRuntimes)
```

2021-07-22 07:47 UTC, Kibnet commented on SkillChat.Server/NETVersionComparison.cs
> +                            if (VARIABLE.Patch >= cfgRuntime.Patch)
Неверное условие. Подойдёт любая версия патча, а у тебя только больше или равно.
В ситуации когда в конфиге 5.0.9 и у тебя установлена только 5.0.8 метод вернёт 5.0.9 и прога крашнется.

2021-07-22 09:05 UTC, Kibnet commented on SkillChat.Server/NETVersionComparison.cs
> +                    });
```suggestion
                    var match = Regex.Match(e.Data, "(?<Name>Microsoft\\.[^.]+\\.[^. ]+)\\s+(?<Version>([0-9a-z-]+\\.)+[0-9a-z-]+)");
                    if (match.Success)
                    {
                        runtimesInstaled.Add(new Runtime()
                        {
                            Name = match.Groups["Name"].Value,
                            Version = match.Groups["Version"].Value,
                        });
                    }
```

2021-07-27 12:47 UTC, Kibnet requested changes
Нужно ещё доработать, пока даже не работает как надо

2021-07-27 12:47 UTC, Kibnet commented on SkillChat.Server/DotNetVersionHelper.cs
> +                        runtimesNETCoreInstaled.Add(new Version(match.Groups["Version"].Value));
Тут падает с исключением на версии 6.0.0-preview.5.21301.5.
Вероятно нам не подходит стандартный класс Version )))
Предлагаю взять эту библиотеку https://github.com/adamreeve/semver.net 
Она мощная и умеет всё что нам нужно. Там в документации даже есть крутая штука, которая прям для нас Range.MaxSatisfying.

2021-07-27 12:47 UTC, Kibnet commented on SkillChat.Server/DotNetVersionHelper.cs
> +            _NETCoreRuntimes = GetNETCorePackageList();
Настойчиво рекомендую этот список получать в конструкторе класса, а не внутри метода поиска подходящего.

2021-07-27 12:47 UTC, Kibnet commented on SkillChat.Server/DotNetVersionHelper.cs
> +        public List<Version> GetNETCorePackageList()
Этот метод лучше вынести в отдельный класс и интерфейс. Передавать его экземпляр через интерфейс в конструктор DotNetVersionHelper. И там уже дёргать метод интерфейса.

2021-07-27 12:47 UTC, Kibnet commented on SkillChat.Server/DotNetVersionHelper.cs
> +            List<Version> _NETCoreRuntimes = new List<Version>();
В этой инициализации нет никакого смысла, следующей строчкой ты перезаписываешь переменную.

2021-07-27 12:47 UTC, Kibnet commented on SkillChat.Server/DotNetVersionHelper.cs
> +                    return _NETCoreRuntimes.First(v => v.Major == cfgVersion.Major && (v.Minor == cfgVersion.Minor || v.Minor == cfgVersion.Minor + 1)).ToString();
Условия для выбора подходящей версии неверные. Минорная может быть и больше чем +1 и это тоже норм. Лучше использовать сравнение с диапазоном.

2021-08-01 10:41 UTC, closed without merging