feat: Добавил фичу "Редактирование выбранного сообщения"
SkillChat/SkillChat pull request #61
Opened 2021-08-04 15:44 UTC by KlinskiyDD

Можно также редактировать последнее сообщение нажав на клавишу «вверх» при выделенном окне ввода.

Единственное, что у меня совершенно не получился дизайн меню. Не могу скруглить его, а также добавить цвет выделения MenuItem.

Еще одна проблема связанна с выделением своего сообщения. В авалони существует стандартное ContextMenu для TextBox.
Я скрыл его, чтобы оно не вылезало, но тогда меню которое я вызываю из Stackpanel можно вызвать только нажатием правой кнопки мышки на любом краю сообщения, а по центру не работает.

2021-08-05 16:19 UTC, Kozlov-AE requested changes
Не нашел изменений в модели сообщения в БД.
Присутствует неиспользуемый код.
В остальном вроде все ок)

2021-08-05 16:19 UTC, Kozlov-AE commented on SkillChat.Client.ViewModel/MessageViewModel.cs
> +    public class EditedUserMessageViewModel : UserMessageViewModel { }
Без ссылок. На удаление

2021-08-05 16:19 UTC, Kozlov-AE commented on SkillChat.Interface/HubMessage.cs
> +        public HubMessage(string id, string chatId, string message)
Переименуй в HubEditedMessage, что бы не путаться. Все равно создал уже новую модель

2021-08-05 16:19 UTC, Kozlov-AE commented on SkillChat.Server/Hubs/ChatHub.cs
> +                await Clients.Group(_loginedGroup).SendAsync(new ReceiveMessage
Можно было бы отправлять только Id и текст. А у вьюмодели на клиенте обновлять текст и ставить галочку edited

2021-08-05 17:34 UTC, KlinskiyDD commented on SkillChat.Client.ViewModel/MessageViewModel.cs
> +        public bool Selected { get; set; }
Сначала делал через вьмодели, а потом посоветовался с Пашей и он подсказал, что можно через bool.

2021-08-05 18:52 UTC, KlinskiyDD commented on SkillChat.Client.ViewModel/MainWindowViewModel.cs
> +                        foreach (var messages in Messages)
Если прилепить сюда реверс, то будет выбираться последнее сообщение из самого первого блока сообщений. 

А есть существенная разница между foreach и for?

2021-08-05 18:59 UTC, KlinskiyDD commented on SkillChat.Client.ViewModel/MainWindowViewModel.cs
> +                            await _hub.SendEditedMessage(new HubMessage(_idEditMessage, ChatId, MessageText)); ///Отправка отредактированного сообщения
Я не подумал об этом. Сейчас реализую это.

2021-08-05 19:17 UTC, KlinskiyDD commented on SkillChat.Server/Hubs/ChatHub.cs
> +                await Clients.Group(_loginedGroup).SendAsync(new ReceiveMessage
Да, ты прав, так и сделаю. + время редактирования

2021-08-05 19:42 UTC, KlinskiyDD commented on SkillChat.Client.ViewModel/MainWindowViewModel.cs
> +                try
+

2021-08-05 19:43 UTC, KlinskiyDD commented on SkillChat.Client.ViewModel/MainWindowViewModel.cs
> +                try
+

2021-08-05 19:43 UTC, KlinskiyDD commented on SkillChat.Client.ViewModel/MainWindowViewModel.cs
> +                            await _hub.SendEditedMessage(new HubMessage(_idEditMessage, ChatId, MessageText)); ///Отправка отредактированного сообщения
+

2021-08-05 19:43 UTC, KlinskiyDD commented on SkillChat.Client.ViewModel/MessageViewModel.cs
> +    public class EditedMyMessageViewModel: MessageViewModel { }
+

2021-08-05 19:43 UTC, KlinskiyDD commented on SkillChat.Client.ViewModel/MessageViewModel.cs
> +    public class EditedUserMessageViewModel : UserMessageViewModel { }
+

2021-08-05 19:43 UTC, KlinskiyDD commented on SkillChat.Interface/HubMessage.cs
> +        public HubMessage(string id, string chatId, string message)
+

2021-08-05 19:44 UTC, KlinskiyDD commented on SkillChat.Server/Hubs/ChatHub.cs
> +                await Clients.Group(_loginedGroup).SendAsync(new ReceiveMessage
+

2021-08-06 07:38 UTC, Kozlov-AE approved these changes
Все ок, комменты отправил в ЛС в телегу.

2021-08-06 07:43 UTC, Kozlov-AE reviewed
тестовый комент

2021-08-06 08:14 UTC, Kozlov-AE requested changes

2021-08-06 08:14 UTC, Kozlov-AE commented on SkillChat.Server/Hubs/ChatHub.cs
> +        public async Task SendEditedMessage(HubMessage hubMessage)
Ему стоит принимать EditedHubMessage. И отправлять всем пользователям ID и текст измененного сообщения, а не сообщение. И в MainViewModel должна быть подписка на приме измененного сообщения, при получении которого она будет искать это сообщение по ID и редактировать его как надо

2021-08-06 08:14 UTC, Kozlov-AE commented on SkillChat.Server/Hubs/ChatHub.cs
> +                    await Clients.Group(_loginedGroup).SendAsync(new ReceiveMessage
Сделай модель ReceivedEditedMessage и с ним работай. Не наследуй его от RecivedMessage, это совсем разные модели.

2021-08-06 08:14 UTC, Kozlov-AE commented on SkillChat.Client.ViewModel/MessageViewModel.cs
> +        public void SelectEditMessage()
Это работа для вьюмодели. Не надо сюда этот метод совать.

2021-08-06 08:14 UTC, Kozlov-AE commented on SkillChat.Client.ViewModel/MainWindowViewModel.cs
> +                        if (data.Edited)
Добавь подписку на получение модели измененного сообщения (id сообщения и новый текст) и там ищи это сообщение, а не при каждом новом сообщении делай это

2021-08-06 22:00 UTC, Kozlov-AE approved these changes
Вроде все ок. Ток забыл удалить лишние методы из мэйнвьюмодел. Ну и у павлв по поводу ревизий таблицы сообщений поинтересуйся (я думаю можно убрать из БД поле "редактировано"

2021-08-08 16:51 UTC, UnluckyD submitted a review, later dismissed

2021-08-09 14:40 UTC, KlinskiyDD commented on SkillChat.Client.ViewModel/MainWindowViewModel.cs
> +        public void EditSelectMessage()
он используется в MessageViewModel для выбора сообщения, которое будет редактироваться

2021-08-09 23:13 UTC, Kibnet reviewed
По работе есть замечания:
1. В контекстном меню на сообщении есть кнопка "цитировать", она не работает, поэтому она там не нужна.
2. Контекстное меню вызывается только при попадании в центр сообщения, а зона в несколько пикселей по границе не реагирует, видимо нужно переместить контекстное меню выше на уровень или сколько из там.
3. При изменении сообщения, меняется и время, а это неочевидно. Время это мы конечно должны фиксировать и показывать потом даже будем при наведении на карандаш. То есть отображаемое время должно остаться исходное.
4. При переходе в режим редактирования должен отображаться карандаш слева от текста в поле ввода, чтобы понять что мы редактируем, а не пишем новое сообщение.

В целом работает круто!

2021-08-10 17:56 UTC, KlinskiyDD commented on SkillChat.Client.ViewModel/MainWindowViewModel.cs
> +            }, this.WhenAnyValue(m => m.IsConnected, b => b == false));
да
удалил

2021-08-10 18:20 UTC, KlinskiyDD commented on SkillChat.Interface/HubMessage.cs
> +        public string Id { get; set; }
+

2021-08-10 18:21 UTC, KlinskiyDD commented on SkillChat.Interface/ReceiveMessage.cs
> +        public bool Edited { get; set; }
+

2021-08-10 18:21 UTC, KlinskiyDD commented on SkillChat.Server/Hubs/ChatHub.cs
> +
+

2021-08-10 18:22 UTC, KlinskiyDD commented on SkillChat.Server/Hubs/ChatHub.cs
> -
+

2021-08-10 18:23 UTC, KlinskiyDD commented on SkillChat.Server/Hubs/ChatHub.cs
> +                    mes.Text = hubEditedMessage.Message;
+

2021-08-11 11:38 UTC, Kibnet submitted a review, later dismissed
Уже очень хорошо. Есть несколько мелких замечаний.

2021-08-11 11:38 UTC, Kibnet commented on SkillChat.Client.ViewModel/MainWindowViewModel.cs
> +                        messageDictionary.Add(newMessage.Id, newMessage);
Вместо добавление через Add, лучше использовать индексатор, потому что при попытке добавить ключ второй раз будет исключение, а через индексатор просто перезапишется.
```suggestion
                        messageDictionary[newMessage.Id] = newMessage;
```

2021-08-11 11:38 UTC, Kibnet commented on SkillChat.Client.ViewModel/MainWindowViewModel.cs
>                      }
Эта строчка имеет смысл только в if выше, там же где и IsEdited = false;

2021-08-11 11:38 UTC, Kibnet commented on SkillChat.Client.ViewModel/MainWindowViewModel.cs
> +                        newMessage.EditedPostTime = item.EditedPostTime;
Тут напрашивается автомаппер, потому что много полей одинаковых присваиваются

2021-08-11 11:38 UTC, Kibnet commented on SkillChat.Client.ViewModel/MainWindowViewModel.cs
> +                        messageDictionary.Add(newMessage.Id,newMessage);
```suggestion
                        messageDictionary[newMessage.Id] = newMessage;
```

2021-08-11 11:38 UTC, Kibnet commented on SkillChat.Client.ViewModel/MainWindowViewModel.cs
> +        /// Метот выхода из режима редактирования
```suggestion
        /// Метод выхода из режима редактирования
```

2021-08-11 11:38 UTC, Kibnet commented on SkillChat.Client.ViewModel/MainWindowViewModel.cs
> +            if (MessageText != null && idEditMessage != null)
А что это за ситуация когда MessageText равен null? Зачем это сдесь проверяем?
```suggestion
            if (idEditMessage != null)
```

2021-08-11 11:38 UTC, Kibnet commented on SkillChat.Client.ViewModel/MainWindowViewModel.cs
> +        /// пользователя и начало редактирование этого сообщения.
```suggestion
        /// пользователя и переход в режим редактирования этого сообщения.
```

2021-08-11 11:38 UTC, Kibnet commented on SkillChat.Client.ViewModel/MainWindowViewModel.cs
> +        ///Переменная для хранения Id редактируемого сообщения</summary>
Неправильный комментарий, нет открывающего тега

2021-08-11 11:38 UTC, Kibnet commented on SkillChat.Client.ViewModel/MainWindowViewModel.cs
> +                message.Selected = false;
Кажется логичным делать это поле false только при выходе из режима редактирования, а не при входе в режим. Тогда на основе этого поля можно будет визуальное выделение сделать в списке сообщений.

2021-08-11 11:38 UTC, Kibnet commented on SkillChat.Client.ViewModel/MainWindowViewModel.cs
> +            if (message.Selected)
Проверять это поле нет смысла, мы же передали саму модель

2021-08-11 11:38 UTC, Kibnet commented on SkillChat.Client.ViewModel/MainWindowViewModel.cs
> +        public bool IsEdited { get; set; }
Кажется это свойство можно сделать зависимым от idEditMessage, так как это флаг его заполненности. Воспользуйся реактивностью.

2021-08-11 11:38 UTC, Kibnet commented on SkillChat.Server.ServiceModel/Molds/MessageMold.cs
> +        public DateTimeOffset EditedPostTime { get; set; }
Я бы предложил более логичное название
```suggestion
        public DateTimeOffset LastEditTime { get; set; }
```

2021-08-11 11:38 UTC, Kibnet commented on SkillChat.Server/Hubs/ChatHub.cs
> +                        Edited = true,
Тут тоже напрашивается автомаппер

2021-08-12 21:05 UTC, merged