feature: #8 auto loading old massages when scrolling
SkillChat/SkillChat pull request #67
Opened 2021-08-15 10:22 UTC by UnluckyD

Данный код автоматически подгружает старые сообщения и немного прокручивает вниз. Что бы было совсем хорошо - было бы не плохо задавать положение скрола напрямую, находя разницу между его новым размером и старым (До подгрузки сообщений). Но нужный параметр в Avalonia.Controls.ScrollViewer имеет уровень доступа protected, что не позволяет этого сделать. Из последних изменений:
1) исправлена двойная загрузка сообщений при старте клиента. А так же положение скрола где то в центре истории сообщений, теперь он прокручивается на последнее сообщение.
2) при скролинге вверх при прогргузке всех сообщений, скрол больше не отскакивает ниже, будто подгрузил ещё сообщений.

2021-08-19 16:26 UTC, KlinskiyDD approved these changes
Проверил, все работает. Вопросов к коду у меня нет.

2021-08-20 12:22 UTC, EgorTrubnikov approved these changes

2021-08-21 20:43 UTC, Kibnet requested changes
1. Проблема в том, что размер окна может быть разным и если количество сообщений при первой загрузке не достаточно чтобы появился скролл, то человек не сможет загрузить предыдущие сообщений, так как не сможет скролл сдвинуть.
2. При подгрузке сообщений окно скролла сдвигается выше на экран, а должно остаться там же где и было. Проблема скорее всего в рассчитываемых значениях сдвига.

2021-08-21 20:43 UTC, Kibnet commented on SkillChat.Client/Views/MainWindow.xaml.cs
> +                vm.SettingsViewModel.LastVerticaloffsetmax = verticaloffsetmax;
Кажется тут что-не так, потому что проматывается не туда куда надо а на страницу выше

2021-08-28 10:36 UTC, Kibnet approved these changes
Всё хорошо работает. Вливаю.

2021-08-28 10:36 UTC, merged