Сделал одну viewModel для всех сообщений
SkillChat/SkillChat pull request #69
Opened 2021-08-23 19:06 UTC by KlinskiyDD

Объединил все MessageViewModel в одну модель.
Добавил стили для сообщений.
Обновил DesignMainWindowViewModel.
Избавился от контейнеров.

2021-08-25 12:04 UTC, UnluckyD approved these changes
👍

2021-08-28 13:51 UTC, KlinskiyDD commented on SkillChat.Client.ViewModel/MessageViewModel.cs
> +        public bool IsFirstMessage { get; set; }
точно, не обратил внимания

2021-08-28 13:51 UTC, KlinskiyDD commented on SkillChat.Client.ViewModel/MainWindowViewModel.cs
> +                            if (Messages[1].UserId!=newMessage.UserId)
+

2021-08-28 13:51 UTC, KlinskiyDD commented on SkillChat.Client.ViewModel/MainWindowViewModel.cs
> +                        Messages.Insert(0, newMessage);
+

2021-09-02 19:17 UTC, KlinskiyDD commented on SkillChat.Client.ViewModel/MessageViewModel.cs
> +        }
+

2021-09-02 19:20 UTC, KlinskiyDD commented on SkillChat.Client.ViewModel/MessageViewModel.cs
> +        }
+

2021-09-02 21:37 UTC, Kibnet requested changes
Ещё чуть докрутить и будет идеально!

2021-09-02 21:37 UTC, Kibnet commented on SkillChat.Client.ViewModel/MainWindowViewModel.cs
> +                        if (Messages.Last().UserId!=data.UserId)
Тут падает, если сообщений нет

2021-09-02 21:37 UTC, Kibnet commented on SkillChat.Client.ViewModel/MessageViewModel.cs
> +                return StatusMessage.SomeonesNotFirstMessage;
Тут можно развернуть в нормальные вложенные if

2021-09-02 21:37 UTC, Kibnet commented on SkillChat.Client.ViewModel/MessageViewModel.cs
> +        public bool IsMyAttachment { get; set; }
Кажется что нигде не используется

2021-09-02 21:37 UTC, Kibnet commented on SkillChat.Client/Styles/MessageStyle.axaml
> +    <Setter Property="Width" Value="150"/>
А правильно ли это задавать размеры элементов, если текст будет больше, что будет?

2021-09-02 21:37 UTC, Kibnet commented on SkillChat.Client/Styles/MessageStyle.axaml
> +    <Setter Property="Width" Value="150"/>
А тут точно нужна ширина? Кажется лишним

2021-09-02 21:37 UTC, Kibnet commented on SkillChat.Client/Styles/MessageStyle.axaml
> +      <Setter Property="Width" Value="150"/>
И тут ширина кажется лишней

2021-09-02 21:37 UTC, Kibnet commented on SkillChat.Client/Utils/StackPanelMarginConverter.cs
> +        }
Можно написать элегантнее через switch expression
```suggestion
        public object Convert(object value, Type targetType, object parameter, CultureInfo culture) =>
            (MessageViewModel.StatusMessage)value switch
            {
                MessageViewModel.StatusMessage.MyFirstMessage => new Thickness(20, 17, 0, 3),
                MessageViewModel.StatusMessage.MyNotFirstMessage => new Thickness(20, 0, 0, 3),
                MessageViewModel.StatusMessage.SomeonesFirstMessage => new Thickness(0, 17, 20, 3),
                MessageViewModel.StatusMessage.SomeonesNotFirstMessage => new Thickness(0, 0, 20, 3),
                _ => null
            };
```

2021-09-03 15:36 UTC, KlinskiyDD commented on SkillChat.Client/Styles/MessageStyle.axaml
> +    <Setter Property="Width" Value="150"/>
Если убрать, то сообщения будут меньше в ширину 
https://puu.sh/I8G09/bd7c5d0920.png

2021-09-03 15:41 UTC, KlinskiyDD commented on SkillChat.Client/Styles/MessageStyle.axaml
> +      <Setter Property="Width" Value="150"/>
тут нужна ширина иначе текст будет показываться неполностью, а если ширину убрать везде, то получится следующее 
https://puu.sh/I8G2X/8560118731.png

2021-09-03 15:44 UTC, KlinskiyDD commented on SkillChat.Client/Utils/StackPanelMarginConverter.cs
> +        }
Это круто, я не знал, что так можно

2021-09-03 16:05 UTC, Mileeena submitted a review, later dismissed

2021-09-04 11:26 UTC, Kibnet commented on SkillChat.Client.ViewModel/MessageViewModel.cs
> +                return StatusMessage.SomeonesNotFirstMessage;
Cам поправил

2021-09-04 11:27 UTC, Kibnet approved these changes
Всё чётко. Это те изменения которые мы так ждали!

2021-09-04 11:27 UTC, merged