Очистка полей регистрации
SkillChat/SkillChat pull request #75
Opened 2021-08-30 03:12 UTC by Mileeena

2021-08-31 11:28 UTC, UnluckyD approved these changes

2021-09-02 03:31 UTC, EgorTrubnikov submitted a review, later dismissed

2021-09-02 12:23 UTC, Kibnet requested changes
Нужно ещё чуть дошлифовать и будет ок

2021-09-02 12:23 UTC, Kibnet commented on SkillChat.Client.ViewModel/MainWindowViewModel.cs
> +                User.Login = RegisterUser.Login;
Раз выше удалил, то и тут удалить надо было, а то странное поведение при переключении между логином и регистрацией, только в одну сторону работает

2021-09-02 12:23 UTC, Kibnet commented on SkillChat.Client.ViewModel/MainWindowViewModel.cs
> +                    RegisterUser.Consent = false;
Лучше вынести в метод Clear для RegisterUser
```suggestion
                    //Очистка полей регистрации
                    RegisterUser.Clear();
```

2021-09-03 13:57 UTC, Mileeena commented on SkillChat.Client.ViewModel/MainWindowViewModel.cs
> +                    RegisterUser.Consent = false;
> Нужно ещё чуть дошлифовать и будет ок

Сделано

2021-09-04 07:33 UTC, Kibnet approved these changes
Всё супер!

2021-09-04 07:33 UTC, merged