Тест
SkillChat/SkillChat pull request #83
Opened 2021-09-06 07:55 UTC by KlinskiyDD

2021-09-09 14:45 UTC, Mileeena submitted a review, later dismissed

2021-09-12 19:19 UTC, EgorTrubnikov approved these changes
Дима, привет. Всё работает. Ты молодец! 
Есть мнение, что комментарии в коде не нужны, они просто захламляют, надо писать код так, что бы он был понятен без комментариев. 
Мне не хватает комментариев. При обЪявлении переменной или свойства, при описание метода.

2021-09-13 09:00 UTC, Kozlov-AE approved these changes
В целом нормально. Работает вроде хорошо)

2021-09-13 10:29 UTC, UnluckyD approved these changes

2021-09-17 21:07 UTC, Kibnet requested changes
Работает хорошо. Проделана очень большая и сложная работа.
1. Есть пару багов, отметил в комментах знаком 🪲.
2. В разных местах одно и тоже названо по разному, нужно привести к единому "Quoted".
3. Есть несколько мест с откровенным копипастом, нужно вынести в методы для переиспользования.

2021-09-17 21:07 UTC, Kibnet commented on SkillChat.Server/Hubs/ChatHub.cs
> +                IdReplyMessage = IdReplyMessage
Тут вместо идентификатора нужно послать полноценное сообщение, загрузив его предварительно из базы

2021-09-17 21:07 UTC, Kibnet commented on SkillChat.Server/Hubs/ChatHub.cs
> +                        IdReplyMessage=IdReplyMessage
Тут вместо идентификатора нужно послать полноценное сообщение, загрузив его предварительно из базы

2021-09-17 21:07 UTC, Kibnet commented on SkillChat.Client.ViewModel/SendAttachmentsViewModel.cs
> +            var mw = Locator.Current.GetService<MainWindowViewModel>();
Тут выглядит не очень, но проблема в самом окошке, которое дублирует функционал основного окна, поэтому пока ок.

2021-09-18 12:10 UTC, KlinskiyDD commented on SkillChat.Server.ServiceInterface/ChatService.cs
> +                    }
+

2021-09-18 15:03 UTC, KlinskiyDD commented on SkillChat.Client.ViewModel/MenuItemObject.cs
> +    public class MenuItemObject : MenuObservableObject
+

2021-09-18 15:10 UTC, KlinskiyDD commented on SkillChat.Client.ViewModel/MainWindowViewModel.cs
>                          }
+

2021-09-18 15:10 UTC, KlinskiyDD commented on SkillChat.Client.ViewModel/MainWindowViewModel.cs
> +                            newMessage.QuotedMessageViewModel = messageDictionary[data.IdReplyMessage];
+

2021-09-18 15:10 UTC, KlinskiyDD commented on SkillChat.Client.ViewModel/MainWindowViewModel.cs
> +                        }
+

2021-09-18 15:10 UTC, KlinskiyDD commented on SkillChat.Server.ServiceInterface/ChatService.cs
> +                    quotedMessage.UserNickName = string.IsNullOrWhiteSpace(user.DisplayName) ? user.Login : user.DisplayName;
+

2021-09-18 15:12 UTC, KlinskiyDD commented on SkillChat.Server/Hubs/ChatHub.cs
> +                IdReplyMessage = IdReplyMessage
+

2021-09-18 15:12 UTC, KlinskiyDD commented on SkillChat.Server/Hubs/ChatHub.cs
> +                        IdReplyMessage=IdReplyMessage
+

2021-09-18 15:12 UTC, KlinskiyDD commented on SkillChat.Client.ViewModel/MainWindowViewModel.cs
> +                            }
+

2021-09-18 21:18 UTC, Kibnet commented on SkillChat.Client.ViewModel/MainWindowViewModel.cs
> +                            }
Добавление сделал, а обновление не сделал. 🕵️‍♂️

2021-09-18 21:22 UTC, Kibnet commented on SkillChat.Client.ViewModel/MainWindowViewModel.cs
> +                            newMessage.QuotedMessageViewModel = messageDictionary[data.IdReplyMessage];
Вообще не то сделал. В словарь не добавил при отсутствии(потенциальное падение при прямом вызове по ключу), старое не обновил при наличии.

2021-09-18 21:24 UTC, Kibnet commented on SkillChat.Client.ViewModel/MainWindowViewModel.cs
> +                                await _hub.UpdateMessage(new HubEditedMessage(idEditMessage, ChatId, MessageText), IdReplyMes); ///Отправка отредактированного сообщения
Я посмотрел историю по коммитам и вижу что изначально всё было правильно. Но потом ты зачем то вынес этот параметр из HubEditedMessage, теперь выглядит коряво, ибо модель размазана по разным места. Первый вариант был правильнее.

2021-09-18 21:25 UTC, Kibnet commented on SkillChat.Client.ViewModel/MainWindowViewModel.cs
> +                                await _hub.SendMessage(new HubMessage(ChatId, MessageText), IdReplyMes);
Я посмотрел историю по коммитам и вижу что изначально всё было правильно. Но потом ты зачем то вынес этот параметр из HubMessage, теперь выглядит коряво, ибо модель размазана по разным места. Первый вариант был правильнее.

2021-09-18 21:28 UTC, Kibnet commented on SkillChat.Client.ViewModel/MainWindowViewModel.cs
> +                                }).ToList();
Я про то что можно удалить
```
quotedMessage.UserNickname = item.QuotedMessage.UserNickName;
```
оно автомаппером делается

2021-09-19 09:45 UTC, KlinskiyDD commented on SkillChat.Client.ViewModel/MainWindowViewModel.cs
> +                                await _hub.UpdateMessage(new HubEditedMessage(idEditMessage, ChatId, MessageText), IdReplyMes); ///Отправка отредактированного сообщения
Исправил, думал, что наоборот будет лучше.

2021-09-19 13:28 UTC, KlinskiyDD commented on SkillChat.Client.ViewModel/MainWindowViewModel.cs
> +                                await _hub.SendMessage(new HubMessage(ChatId, MessageText), IdReplyMes);
Исправил

2021-09-19 13:30 UTC, KlinskiyDD commented on SkillChat.Client.ViewModel/MainWindowViewModel.cs
> +                                }).ToList();
Точно, я не заметил. Исправил.

2021-09-19 13:36 UTC, KlinskiyDD commented on SkillChat.Client.ViewModel/MainWindowViewModel.cs
> +                            newMessage.QuotedMessageViewModel = quotedMessage;
Исправил

2021-09-19 13:37 UTC, KlinskiyDD commented on SkillChat.Client.ViewModel/MainWindowViewModel.cs
> +        public MessageViewModel SelectedReplyMessage { get; set; }
Согласен, исправил.

2021-09-19 13:40 UTC, KlinskiyDD commented on SkillChat.Client.ViewModel/MainWindowViewModel.cs
> +        public Dictionary<string, MessageViewModel> messageDictionary = new Dictionary<string, MessageViewModel>();
Я раньше использовал его в MessageViewModel, но в последствии отказался от этой идеи, а исправить уровень доступа забыл.

Сейчас исправил.

2021-09-19 13:41 UTC, KlinskiyDD commented on SkillChat.Client.ViewModel/MainWindowViewModel.cs
> +        public void ReplyMessage(MessageViewModel message)
Исправил

2021-09-19 13:48 UTC, KlinskiyDD commented on SkillChat.Client.ViewModel/MainWindowViewModel.cs
> +            SelectedReplyMessage = new MessageViewModel();
Исправил

2021-09-19 13:53 UTC, KlinskiyDD commented on SkillChat.Client.ViewModel/MessageViewModel.cs
> +        public bool IsQuotedMessage { get; set; }
Исправил

2021-09-19 13:54 UTC, KlinskiyDD commented on SkillChat.Client.ViewModel/MessageViewModel.cs
> +        }
Исправил

2021-09-19 13:59 UTC, KlinskiyDD commented on SkillChat.Client/Styles/MessageStyle.xaml
> +    <Style Selector="TextBox.replyMessage">
Исправил

2021-09-19 14:02 UTC, KlinskiyDD commented on SkillChat.Client/Views/ReplyMessage.axaml.cs
> +    public partial class ReplyMessage : UserControl
Исправил

2021-09-19 14:02 UTC, KlinskiyDD commented on SkillChat.Interface/IChatHub.cs
> +        Task UpdateMessage(HubEditedMessage hubEditedMessage, string IdReplyMessage);
Исправил

2021-09-19 14:03 UTC, KlinskiyDD commented on SkillChat.Server.Domain/Message.cs
> +        public string IdReplyMessage { get; set; }
Исправил

2021-09-19 16:42 UTC, KlinskiyDD commented on SkillChat.Client.ViewModel/MainWindowViewModel.cs
> +        public bool IsSelectReplyMessage { get; set; }
Исправил

2021-09-22 09:26 UTC, Kibnet approved these changes

2021-09-22 09:26 UTC, Kibnet commented on SkillChat.Client/SkillChat.Client.csproj
> +    </ItemGroup>
Тут беспорядок

2021-09-22 09:26 UTC, Kibnet commented on SkillChat.Server/Hubs/ChatHub.cs
> +        }
Почти полный копипаст из ChatService. Можно было бы вынести общий метод без финального маппинга, а маппинг у же по месту применять через Select

2021-09-22 09:26 UTC, Kibnet commented on SkillChat.Server/Hubs/ChatHub.cs
> +
Слишком много пустых строк

2021-09-22 09:26 UTC, Kibnet commented on SkillChat.Server/Hubs/ChatHub.cs
> +                    UserNickname = user.DisplayName,
Рассинхрон, в одном месте UserNickname, в другом DisplayName. Нужно единообразие.

2021-09-22 09:26 UTC, Kibnet commented on SkillChat.Server/SkillChat.Server.csproj
> +        <PackageReference Include="Splat" Version="13.1.10" />
Splat предназначен только для клиентских приложений из-за своего удобства. На сервере есть и так встроенные средства для инверсии зависимостей. Нужно выпилить.

2021-09-22 09:31 UTC, merged