Feature/#13 ability to select multiple messages in the chat window
SkillChat/SkillChat pull request #89
Opened 2021-09-13 16:23 UTC by KlinskiyDD

Сверстал начальный дизайн для фичи "Выбор сообщений"

2021-09-19 16:13 UTC, Mileeena approved these changes
Хорошая работа!

2021-09-23 11:30 UTC, UnluckyD submitted a review, later dismissed

2021-09-24 22:43 UTC, Kibnet requested changes
1. Во время выбора сообщений остаются доступны редактирование и ответ на сообщение, из-за чего панель может быть увеличена по высоте. Эти команды должны быть недоступны пока включен режим выбора сообщений
2. Порядок выбора сообщений влияет на порядок скопированных сообщений, порядок должен быть как в окне сообщений

2021-09-24 22:43 UTC, Kibnet commented on SkillChat.Client.ViewModel/MessageViewModel.cs
> +}
Зачем тут меняли просто так?

2021-09-24 22:43 UTC, Kibnet commented on SkillChat.Client.ViewModel/MessageViewModel.cs
> +            Mv = Locator.Current.GetService<MainWindowViewModel>();
Зачем, если нигде не используется?

2021-09-24 22:43 UTC, Kibnet commented on SkillChat.Client.ViewModel/MessageViewModel.cs
> +        }
Вместо этого, можно было бы сделать реактивную подписку на изменение этого поля в котором делать то что нужно.
Детали работы selectMsgMode нужно инкапсулировать, и вызывать просто методы Select(this) и Unselect(this), счётчик должен сам там высчитваться внутри.

2021-09-24 22:43 UTC, Kibnet commented on SkillChat.Client.ViewModel/MessageViewModel.cs
> +            selectMsgMode = Locator.Current.GetService<SelectMessages>();
Мне кажется что такие вещи в конструкторе ломают превьювер с дизайн вью моделью. Лучше вынести ближе к использованию.

2021-09-24 22:43 UTC, Kibnet commented on SkillChat.Client.ViewModel/SelectMessages.cs
> +        public int CountCheckedMsg { get; set; }
Можно сделать вычислимым беря Count из SelectedMessagesTempCollection

2021-09-24 22:43 UTC, Kibnet commented on SkillChat.Client.ViewModel/SelectMessages.cs
> +        public ObservableCollection<MessageViewModel> SelectedMessagesTempCollection { get; set; }
Название очень страшное
```suggestion
        public ObservableCollection<MessageViewModel> SelectedCollection { get; set; }
```

2021-09-24 22:43 UTC, Kibnet commented on SkillChat.Client.ViewModel/SelectMessages.cs
> +                        text += txt;
Вместо конкатенации лучше использовать StringBuilder, он под капотом использует буффер, и заполняет его. Если нужно только склеивать строки, то он в 10 раз быстрее.

2021-09-24 22:43 UTC, Kibnet commented on SkillChat.Client.ViewModel/SelectMessages.cs
> +                    foreach (var message in SelectedMessagesTempCollection)
Строки будут в том порядке в котором их выделяли, а не в том в котором они на экране

2021-09-24 22:43 UTC, Kibnet commented on SkillChat.Client.ViewModel/SelectMessages.cs
> +            }
Зачем пробегать по всем, если у нас есть список тех у кого включено - SelectedMessagesTempCollection

2021-09-24 22:43 UTC, Kibnet commented on SkillChat.Client.ViewModel/SkillChat.Client.ViewModel.csproj
> +        <PackageReference Include="Avalonia" Version="0.10.7" />
Авалонии в этом проекте быть не должно!

2021-09-24 22:43 UTC, Kibnet commented on SkillChat.Client.ViewModel/MessageViewModel.cs
> +    public class MessageViewModel: IEquatable<MessageViewModel>
Зачем этот интерфейс тут?

2021-09-27 03:52 UTC, EgorTrubnikov commented
> 1. Во время выбора сообщений остаются доступны редактирование и ответ на сообщение, из-за чего панель может быть увеличена по высоте. Эти команды должны быть недоступны пока включен режим выбора сообщений
> 2. Порядок выбора сообщений влияет на порядок скопированных сообщений, порядок должен быть как в окне сообщений
---------------------------
>1. сделал
>2. сделал

2021-09-27 03:53 UTC, EgorTrubnikov commented on SkillChat.Client.ViewModel/MessageViewModel.cs
> +}
Не знаю. Вернул пустую строчку для лучшего восприятия кода.

2021-09-27 03:53 UTC, EgorTrubnikov commented on SkillChat.Client.ViewModel/MessageViewModel.cs
> +            Mv = Locator.Current.GetService<MainWindowViewModel>();
Удалил.

2021-09-27 03:54 UTC, EgorTrubnikov commented on SkillChat.Client.ViewModel/MessageViewModel.cs
> +        }
Сделал подписку

2021-09-27 03:54 UTC, EgorTrubnikov commented on SkillChat.Client.ViewModel/MessageViewModel.cs
> +            selectMsgMode = Locator.Current.GetService<SelectMessages>();
Сделал

2021-09-27 03:55 UTC, EgorTrubnikov commented on SkillChat.Client.ViewModel/SelectMessages.cs
> +        public int CountCheckedMsg { get; set; }
Сделали

2021-09-27 03:55 UTC, EgorTrubnikov commented on SkillChat.Client.ViewModel/SelectMessages.cs
> +        public ObservableCollection<MessageViewModel> SelectedMessagesTempCollection { get; set; }
Переименовал

2021-09-27 03:55 UTC, EgorTrubnikov commented on SkillChat.Client.ViewModel/SelectMessages.cs
> +                        text += txt;
Сделал

2021-09-27 03:56 UTC, EgorTrubnikov commented on SkillChat.Client.ViewModel/SelectMessages.cs
> +                    foreach (var message in SelectedMessagesTempCollection)
Сделал сортировку по полю дата

2021-09-27 03:56 UTC, EgorTrubnikov commented on SkillChat.Client.ViewModel/SelectMessages.cs
> +            }
Переписал

2021-09-27 03:56 UTC, EgorTrubnikov commented on SkillChat.Client.ViewModel/SkillChat.Client.ViewModel.csproj
> +        <PackageReference Include="Avalonia" Version="0.10.7" />
Сделал через интерфейс

2021-09-27 03:56 UTC, EgorTrubnikov commented on SkillChat.Client.ViewModel/MessageViewModel.cs
> +    public class MessageViewModel: IEquatable<MessageViewModel>
Удалил

2021-09-27 08:27 UTC, Kibnet requested changes
Уже круто, осталось исправить 3 замечания и можем вливать

2021-09-27 08:27 UTC, Kibnet commented on SkillChat.Client.ViewModel/SelectMessages.cs
> +        }
На самом деле вместо этого всего можно в биндингах использовать отрицание через восклицательный знак
`{Binding !IsTurnedSelectMode}`

2021-09-27 08:27 UTC, Kibnet commented on SkillChat.Client/Styles/SendMessageStyle.xaml
> +		<Setter Property="FontSize" Value="17"/>
Нафига тут увеличение? Это по дизайну? У меня некрасиво прыгает при нажатии.

2021-09-27 08:27 UTC, Kibnet commented on SkillChat.Client/Views/SelectMessageBorderControl.axaml
> +		</Grid>
Если окно будет узкое, то кнопка отмена уезжает за край экрана, а кнопка копирования только наполовину видна. Нужно сделать так чтобы они всегда были на виду. При сужении они могут перекомпоноваться, попробуй WrapPanel

2021-09-27 18:26 UTC, KlinskiyDD commented on SkillChat.Client/Views/SelectMessageBorderControl.axaml
> +		</Grid>
Исправил

2021-09-28 03:17 UTC, EgorTrubnikov commented on SkillChat.Client.ViewModel/SelectMessages.cs
> +        }
Сделал. Очень изящный и логичный вариант.

2021-09-30 08:21 UTC, KlinskiyDD commented on SkillChat.Client/Styles/SendMessageStyle.xaml
> +		<Setter Property="FontSize" Value="17"/>
Исправил

2021-09-30 08:30 UTC, EgorTrubnikov submitted a review, later dismissed
Работа над замечаниями произведена.

2021-09-30 22:21 UTC, Kibnet submitted a review, later dismissed

2021-09-30 22:21 UTC, Kibnet commented on SkillChat.Client/Utils/SetMessagesToClipboard.cs
> +    class SetMessagesToClipboard : IClipboardMessage
Мне кажется не логичным message в названии этого интерфейса
```suggestion
    class SetMessagesToClipboard : IClipboard
```

2021-09-30 22:21 UTC, Kibnet commented on SkillChat.Client/Views/SelectMessageBorderControl.axaml
> +                Classes="SelectMessageBorder CopyToClipboard" ToolTip.Tip="Скопировать в буфер обмена">
Тултип работает нестабильно. Или это только у меня?

2021-09-30 22:30 UTC, merged