Пофиксил баг
SkillChat/SkillChat pull request #96
Opened 2021-09-20 19:10 UTC by EgorTrubnikov

Суть проблемы:
Если разлогиниться в режиме редактирования и залогиниться под другого, то при вводе первого сообщения будет редактироваться то сообщение, при редактировании которого был совершён акт разлогинивания.
Решение:
Добавил выполнение команды EndEditCommand в команду выхода из профиля SignOutCommand

2021-09-22 00:47 UTC, Mileeena approved these changes

2021-09-22 13:08 UTC, UnluckyD approved these changes

2021-09-22 21:41 UTC, Kibnet requested changes
Часть задачи сделана. А вторая нет. Где проверка принадлежности редактируемого сообщения на бэке?

2021-09-23 04:05 UTC, EgorTrubnikov commented
> Часть задачи сделана. А вторая нет. Где проверка принадлежности редактируемого сообщения на бэке?

В соответствии с моим пониманием задачи, вторая часть - проверка принадлежности редактируемого сообщения на бэке, после необходимых действий при решении первой, по факту становится не актуальной. 
 - При выходе из профиля через меню программы - режим редактирования отключается (в этом моё решение);
 - При падении сервера (я это состояние имитировал простым отключением) и/или при закрытии клиента, при повторном входе режим редактирования не активен;
В свете двух изложенных выше способов проверки работоспособности предложенного решения и фактических результатов эти тестов и появилось понимание о том, что задача решена полностью.

2021-09-23 08:45 UTC, Kibnet commented
@EgorTrubnikov Если бы мир состоял только из честных людей, то твои доводы были бы верными. А так у нас остаётся уязвимость на бэкенде, которая позволит любому владеющиму средствами отправки запросов типа Postman или Swagger менять чужие сообщения. Я считаю что это критическая уязвимость которую обязательно нужно устранить.

2021-09-24 18:54 UTC, Kibnet requested changes
Уязвимость не закрыта, передаётся избыточная информация

2021-09-24 18:54 UTC, Kibnet commented on SkillChat.Client.ViewModel/MainWindowViewModel.cs
> +                                await _hub.UpdateMessage(new HubEditedMessage(idEditMessage, User.Id, ChatId, MessageText)); //Отправка отредактированного сообщения
Передавать идентификатор пользователя не имеет смысла, так его тоже можно подделать. Убери

2021-09-24 18:54 UTC, Kibnet commented on SkillChat.Server/Hubs/ChatHub.cs
> +                if (mes.Text.Trim() != hubEditedMessage.Message.Trim() && mes.UserId == hubEditedMessage.UserId)
Надо сравнивать не с присланным идентификатором пользователя а с тем что лежит в контексте соединения uid

2021-09-24 20:50 UTC, Kibnet approved these changes
Теперь всё работает как надо. 👏

2021-09-24 20:51 UTC, merged